### ISSUE TITLE
Error when running docker_run_and_create_wallet.sh

### ISSUE THREAD

**Issue by lo00l** [CityOfZion/neo-privatenet-docker#62] opened 2018-11-22 09:26 UTC
Hi there.

I try to run my own NEO privnet following instructions from readme.

I have successfully built and run docker container. Then I tried this:
```./docker_run_and_create_wallet.sh``` and got the following error:
```bash
Starting container...
6ecdf34e49cfe2187140e01f5ab55a0a011fd7b1098b62d1d0e2289cbc55ba12
Waiting 10 seconds to let consensus nodes start...
Starting script to claim NEO and GAS...
docker exec -it neo-privnet python3.6 /neo-python/claim_neo_and_gas_fixedwallet.py

Traceback (most recent call last):
  File "/neo-python/claim_neo_and_gas_fixedwallet.py", line 46, in <module>
    from neo.Prompt.Commands.Send import construct_and_send
ImportError: cannot import name 'construct_and_send'

Copying wallet file and wif key out of Docker container...
Error: No such container:path: neo-privnet:/tmp/wif

--------------------

All done! You now have 2 files in the current directory:

  neo-privnet.wallet .. a wallet you can use with neo-python (pwd: coz)
  neo-privnet.wif ..... a wif private key you can import into other clients

Enjoy!
```

After this file `neo-privnet.wallet` is present in `/neo-python` directory but there's no `neo-privnet.wif` file.

And finally I have no NEO and no GAS in the wallet. What I try:
```bash
root@neo-privnet:/neo-python# np-prompt -p
Privatenet useragent '/NEO:2.8.0/', nonce: 1092010408
[I 181122 09:22:11 LevelDBBlockchain:112] Created Blockchain DB at /root/.neopython/Chains/privnet 
[I 181122 09:22:11 LevelDBBlockchain:156] Current stored headers empty, re-creating from stored blocks...
[I 181122 09:22:11 NotificationDB:73] Created Notification DB At /root/.neopython/Chains/privnet_notif 
NEO cli. Type 'help' to get started


neo> open wallet neo-privnet.wallet                                                                                                                                                                         
[password]> ***                                                                                                                                                                                             
Opened wallet at neo-privnet.wallet
neo> wallet rebuild                                                                                                                                                                                         
neo> send c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b AZ81H31DMWzbSnFDLFkzh9vHwaDLayV7fU 10                                                                                            
[E 181122 09:22:59 Wallet:1071] insufficient funds for asset id: c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b 
[D 181122 09:22:59 Send:162] insufficient funds
```

Why this happens? Maybe I do something wrong? How to fix this?

Thank you!

**Comment by nunojusto** [comment] 2018-12-05 14:24
The problem is here
https://github.com/CityOfZion/neo-privatenet-docker/blob/a4a8f215c3e3a477f76848611cc522fe771ec952/scripts/claim_neo_and_gas_fixedwallet.py#L210
And here
https://github.com/CityOfZion/neo-privatenet-docker/blob/a4a8f215c3e3a477f76848611cc522fe771ec952/scripts/claim_gas_fixedwallet.py#L136

This is because neo-python changed the send to add `sendmany` feature
In this PR
https://github.com/CityOfZion/neo-python/pull/610

**Comment by dinihou** [comment] 2018-12-05 16:18
so what we need to do ??

**Comment by lo00l** [comment] 2018-12-05 16:40
@dinihou I solved this problem by running `git checkout tags/v0.8.1` in `/neo-python` directory. Then I ran `/neo-python/claim_neo_and_gas_fixedwallet.py` again and got test NEO in the wallet. Unfortunately, I couldn't get GAS because there still was an error, but I don't need GAS.

@nunojusto Thank you for reply! This really helped me!

**Comment by nunojusto** [comment] 2018-12-05 17:01
@lo00l That was only a workaround for now. This should be fixed soon.
And you can use the neo-faucet to claim some GAS (go for http://localhost:4002)

**Comment by dinihou** [comment] 2018-12-05 18:34
I successfully claim gas by using 
signature -> broadcast method 
Here :http://docs.neo.org/en-US/network/private-chain.html
It not big deal

**Comment by EliEladElrom** [comment] 2019-01-06 08:27
@dinihou looks like the URL is now broken; https://docs.neo.org/en-US/network/private-chain.md
Can you plz explain what you have done to claim gas?

**Comment by nunojusto** [comment] 2019-01-06 11:41
> @dinihou looks like the URL is now broken; https://docs.neo.org/en-US/network/private-chain.md
> Can you plz explain what you have done to claim gas?

You can follow the backup page.
https://web.archive.org/web/20180418220522/https://docs.neo.org/en-us/node/private-chain.html
The needed part is the step 5.

- You will need neo-gui installed. And point it to the privatenet
- Then need to open one of the wallets of the nodes that are producting blocks.
- That wallet will need 3 of the 4 signatures (available inside protocol.json)
- Then after owning the 'master' wallet, you can transfer to you wallet (create one first)
- After all, you can claim some GAS with a menu option

You can also use [neo-local](https://github.com/CityOfZion/neo-local) project that has a neo-faucet easy to use and claim both NEO and GAS.

**Comment by EliEladElrom** [comment] 2019-01-06 16:33
thnx @dinihou I am on a Mac, which neo-gui is not supported, any other ways you know about to solve this issue.  Any PR where claim_neo_and_gas_fixedwallet.py is fixed?

**Comment by nunojusto** [comment] 2019-01-06 16:49
Yes, there's a PR waiting to be merged
https://github.com/CityOfZion/neo-privatenet-docker/pull/63
Let me try to get an approver/merger...

**Comment by nunojusto** [comment] 2019-01-06 17:03
> thnx @dinihou I am on a Mac, which neo-gui is not supported, any other ways you know about to solve this issue. Any PR where claim_neo_and_gas_fixedwallet.py is fixed?

So... it's now merged. Enjoy

**Comment by EliEladElrom** [comment] 2019-01-06 19:28
@dinihou I can confirm that I was able to claim both NEO & GAS with the latest code. Thank you!

**Closed as completed** 2019-01-18 12:58 UTC
